# Generated by Django 5.0.3 on 2024-03-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "date",
                    models.CharField(
                        choices=[("year", "year"), ("month", "month"), ("day", "day")],
                        max_length=5,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=6
                    ),
                ),
                ("dr", models.CharField(blank=True, max_length=40)),
                ("phone", models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveSmallIntegerField()),
                ("unit", models.CharField(max_length=20)),
                ("male_ref", models.TextField()),
                ("female_ref", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(max_length=20)),
                ("ref", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.patient",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="program.test"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="tests",
            field=models.ManyToManyField(to="program.test"),
        ),
    ]
