# Generated by Django 5.0.3 on 2024-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="female_ref",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="male_ref",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="unit",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
