# Generated by Django 5.0.3 on 2024-03-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0002_alter_test_female_ref_alter_test_male_ref_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="date",
            new_name="dat",
        ),
    ]
