# Generated by Django 5.0.3 on 2024-03-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0003_rename_date_patient_dat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="dat",
            new_name="date",
        ),
    ]
