# Generated by Django 5.0.3 on 2024-03-22 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0004_rename_dat_patient_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="entry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 22, 11, 50, 49, 152537, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
