# Generated by Django 5.0.3 on 2024-03-22 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0005_patient_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="entry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 22, 12, 7, 23, 594283, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
